### PR TITLE
Validate signature scheme is present when decoding TPMT_PUBLIC blobs

### LINKED ISSUE #139: Segfault in ParseAKPublic
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0x56251519dc69]

<redacted>/attest.ParseAKPublic(0x2, 0xc0029c44e0, 0x1a, 0x20, 0xc002a13980, 0x1, 0x1)
        <redacted>/attest/attest.go:244 +0x449 fp=0xc002a63090 sp=0xc002a62fa8 pc=0x56251519dc69
```

Appears to be a deref somewhere in `.RSAParameters.Sign.Hash`.

This input can cause it: `[0 1 0 4 0 1 0 0 0 0 0 6 0 128 0 67 0 16 8 0 0 1 0 1 0 0]`

### PR DESCRIPTION
**Pull request by twitchy-jsonp**
Fixes #139

### CODE REVIEW

File: attest/attest.go [hunk 1]
```diff
@@ -234,10 +234,14 @@ func ParseAKPublic(version TPMVersion, public []byte) (*AKPublic, error) {
 		if err != nil {
 			return nil, fmt.Errorf("parsing TPM public key structure: %v", err)
 		}
+		if pub.RSAParameters.Sign == nil {
```
Comment (ericchiang) [inline attest/attest.go]: One question, what if this is a EC key?

Comment (ericchiang) [reply attest/attest.go]: Would the check be better in the switch statement below?

Comment (twitchy-jsonp) [reply attest/attest.go]: Added validation for both RSA & ECC parameters.
